export const teamMembers = [
  {
    name: "Vihaan Snuhith",
    src: "/public/images/team/Vihaan.jpg",
    title: "Team Lead & Design Head",
    twitter: null,
    linkedin: "https://www.linkedin.com/in/vihaan-snuhith-015714212/",
  },
  {
    name: "Likith A Nayaka",
    src: "public/images/team/Likith.jpg",
    title: "Team Vice Lead & Manufacturing Head",
    twitter: null,
    instagram: null,
    linkedin: "https://www.linkedin.com/in/likhit-a-nayaka-24a487353/",
  },
  {
    name: "Rahul OM",
    src: "public/images/team/Rahul.jpg",
    title: "Aerodynamics Head",
    twitter: null,
    instagram: null,
    linkedin: "https://www.linkedin.com/in/rahul-o-m-b7367a253/",
  },
  {
    name: "Sarthak Sharma",
    src: "public/images/team/Sarthak.jpg",
    title: "Avionics Head",
    twitter: null,
    instagram: null,
    linkedin: "https://www.linkedin.com/in/sarthak-sharma-5ab0a7233/",
  },
  {
    name: "S Venkatesh Shenoy",
    src: "public/images/team/Venkatesh.jpg",
    title: "Flight Test Head",
    twitter: null,
    instagram: null,
    linkedin: "https://www.linkedin.com/in/venkatesh-shenoy-77a978291/",
  },
  {
    name: "Manodnya Korishetty",
    src: "public/images/team/Manodnya.jpeg",
    title: "Inventory and Procurement Head",
    twitter: null,
    instagram: null,
    linkedin: "https://www.linkedin.com/in/manodnya-korishetty-400a48214/",
  },
  {
    name: "Prajwal N",
    src: "public/images/team/Prajwal.jpeg",
    title: "Research & Development Head",
    twitter: null,
    instagram: null,
    linkedin: "https://www.linkedin.com/in/prajwal-n-79a0b025b",
  },
  {
    name: "Yash Saraogi",
    src: "public/images/team/Yash.png",
    title: "Web Development Head",
    twitter: null,
    instagram: null,
    linkedin: "https://www.linkedin.com/in/yashsaraogi05/",
  },
  {
    name: "Kanish",
    src: "public/images/team/Kanish.png",
    title: "Finance Head",
    twitter: null,
    instagram: null,
    linkedin: "https://www.linkedin.com/in/b-l-kanish-699b032b7/",
  },
  {
    name: "Tushar Mongia",
    src: "public/images/team/Tushar.png",
    title: "Sponsorship Head",
    twitter: null,
    instagram: null,
    linkedin: "https://www.linkedin.com/in/tusharm11/",
  },
  {
    name: "Sarvika Raju Chamarthy",
    src: "/images/team/gautam.jpg",
    title: "Social Media Head",
    twitter: null,
    instagram: null,
    linkedin: "https://www.linkedin.com/in/sarvika-raju-chamarthy-b46057281/",
  },
];
