export const teamMembers = [
  // Team Leads
  {
    name: "Likhith N",
    src: "/images/team/Likith.webp",
    title: "Team Lead",
    department: "Leadership",
    linkedin: "https://www.linkedin.com/in/likhit-a-nayaka-24a487353/",
  },
  {
    name: "Sarthak Sharma",
    src: "/images/team/Sarthak.webp",
    title: "Team Lead",
    department: "Leadership",
    linkedin: "https://www.linkedin.com/in/sarthak-sharma-5ab0a7233/",
  },
  
  // All Team Members - One card per person with combined roles
  {
    name: "Aryan",
    src: "/images/team/unknown.webp",
    title: "Aerodynamics",
    department: "Member",
    linkedin: null,
  },
  {
    name: "Sarthak",
    src: "/images/team/Sarthak.webp",
    title: "Aerodynamics & Sponsorship",
    department: "Member",
    linkedin: "https://www.linkedin.com/in/sarthak-sharma-5ab0a7233/",
  },
  {
    name: "Venkatesh",
    src: "/images/team/Venkatesh.webp",
    title: "Design & Pilot",
    department: "Member",
    linkedin: "https://www.linkedin.com/in/venkatesh-shenoy-77a978291/",
  },
  {
    name: "Ajith",
    src: "/images/team/unknown.webp",
    title: "Design",
    department: "Member",
    linkedin: null,
  },
  {
    name: "Manodnya",
    src: "/images/team/Manodnya.webp",
    title: "Manufacturing & Procurement and Inventory",
    department: "Member",
    linkedin: "https://www.linkedin.com/in/manodnya-korishetty-400a48214/",
  },
  {
    name: "Likhith",
    src: "/images/team/Likith.webp",
    title: "Manufacturing & Procurement and Inventory",
    department: "Member",
    linkedin: "https://www.linkedin.com/in/likhit-a-nayaka-24a487353/",
  },
  {
    name: "Sarvika",
    src: "/images/team/sarvika.webp",
    title: "Avionics & Finance and Budgeting",
    department: "Member",
    linkedin: "https://www.linkedin.com/in/sarvika-raju-chamarthy-b46057281/",
  },
  {
    name: "Pranati",
    src: "/images/team/unknown.webp",
    title: "Avionics",
    department: "Member",
    linkedin: null,
  },
  {
    name: "Yash",
    src: "/images/team/Yash.webp",
    title: "Pilot & Website Maintenance",
    department: "Member",
    linkedin: "https://www.linkedin.com/in/yashsaraogi05/",
  },
  {
    name: "Lalitha",
    src: "/images/team/unknown.webp",
    title: "Research",
    department: "Member",
    linkedin: null,
  },
  {
    name: "Annie",
    src: "/images/team/unknown.webp",
    title: "Research",
    department: "Member",
    linkedin: null,
  },
  {
    name: "Pratiksha Poojary",
    src: "/images/team/unknown.webp",
    title: "Social Media",
    department: "Member",
    linkedin: null,
  },
  {
    name: "Madhura",
    src: "/images/team/unknown.webp",
    title: "Social Media",
    department: "Member",
    linkedin: null,
  },
  {
    name: "Shivansh",
    src: "/images/team/unknown.webp",
    title: "Finance and Budgeting & Sponsorship",
    department: "Member",
    linkedin: null,
  },
  {
    name: "Tallam Sai",
    src: "/images/team/unknown.webp",
    title: "Website Maintenance",
    department: "Member",
    linkedin: null,
  },
];
